import { useEffect, useMemo, useState, useSyncExternalStore } from "react";
import { buildPpfExcludedChartHistory } from "@/src/domain/calculations/ppfExcludedChartHistory";
import type { StoreApi } from "zustand/vanilla";

import {
  buildMonthlyProgressChartData,
  buildGeneratedMonthEndSnapshot,
  calculateAllocation,
  calculateCashBalance,
  calculateCashMonthlyMetrics,
  calculateHoldings,
  calculateMonthlyProgressSummaries,
  calculatePortfolioTotal,
  deriveMonthlySnapshotSalary,
  getDefaultMonthlyChartRange,
  getMissingCompletedSnapshotMonths,
  getMonthlySnapshotPriceConfidence,
  getPreviousCompletedMonth,
  isAutoGeneratedSnapshotProvisional,
  shouldReplaceProvisionalSnapshot,
  type GeneratedSnapshotStatus,
  type MonthlyChartCustomRange,
  type MonthlyChartRange,
} from "@/src/domain/calculations";
import {
  decimal,
  normalizeMoney,
  quantityQuantum,
  sumFinancialValues,
} from "@/src/domain/precision";
import {
  getOpeningPositionHistoryDate,
  isTransactionAfterOpeningCutover,
} from "@/src/domain/openingPositions";
import { getTradeQuantityDelta } from "@/src/domain/transactionSemantics";
import { formatLocalCalendarDate } from "@/src/domain/dates";
import {
  calculatePpfPortfolioSummary,
  getLinkedLegacyPpfAssetIds,
} from "@/src/domain/ppf";
import { resolveHistoricalPrice } from "@/src/services/quotes";
import { getPortfolioStore, type PortfolioStoreState } from "@/src/store";
import { historicalQuoteCacheKey, type MonthlySnapshot } from "@/src/types";
import { createId } from "@/src/utils";

function usePortfolioSnapshot(store: StoreApi<PortfolioStoreState>) {
  return useSyncExternalStore(store.subscribe, store.getState, store.getState);
}

export function emptyProgressFormValues() {
  const now = new Date();

  return {
    cashValue: "",
    cryptoValue: "",
    debtValue: "",
    equityValue: "",
    investedValue: "",
    month: `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}`,
    monthlyExpense: "",
    monthlyInvestment: "",
    notes: "",
    portfolioValue: "",
    salary: "",
  };
}

export type ProgressFormValues = ReturnType<typeof emptyProgressFormValues>;
export type ProgressFormErrors = Partial<Record<keyof ProgressFormValues, string>>;

export type ProgressSnapshotAutomationStatus = {
  message: string;
  provisionalMonths: string[];
  snapshot: MonthlySnapshot | null;
  status: GeneratedSnapshotStatus | "idle";
  targetMonth: string;
  warnings: string[];
};

type MonthEndSnapshotAutomationRunResult = {
  createdCount: number;
  incomeRefreshedCount: number;
  lastCompletedMonth: string;
  provisionalCount: number;
  provisionalMonths: string[];
  refreshedCount: number;
  snapshot: MonthlySnapshot | null;
  status: GeneratedSnapshotStatus;
  targetMonths: string[];
  warnings: string[];
};

const inFlightSnapshotAutomationRuns = new WeakMap<
  StoreApi<PortfolioStoreState>,
  Promise<MonthEndSnapshotAutomationRunResult>
>();
const snapshotAutomationEpochs = new WeakMap<StoreApi<PortfolioStoreState>, number>();

type UseProgressInput = {
  historicalPriceFetcher?: typeof resolveHistoricalPrice;
  now?: Date;
  store?: StoreApi<PortfolioStoreState>;
};

function getAvailableSnapshotMonths(snapshots: MonthlySnapshot[]) {
  return [...new Set(snapshots.map((snapshot) => snapshot.month))].sort();
}

function getDefaultCustomChartRange(
  snapshots: MonthlySnapshot[],
): MonthlyChartCustomRange {
  const months = getAvailableSnapshotMonths(snapshots);

  return {
    endMonth: months.at(-1) ?? "",
    startMonth: months[0] ?? "",
  };
}

function normalizeCustomChartRange(
  current: MonthlyChartCustomRange,
  snapshots: MonthlySnapshot[],
) {
  const months = getAvailableSnapshotMonths(snapshots);
  const startMonth = months.includes(current.startMonth)
    ? current.startMonth
    : months[0] ?? "";
  const endMonth = months.includes(current.endMonth)
    ? current.endMonth
    : months.at(-1) ?? "";

  if (startMonth >= endMonth) {
    return {
      endMonth: months.at(-1) ?? "",
      startMonth: months[0] ?? "",
    };
  }

  return { endMonth, startMonth };
}

const requiredNumberFields: Array<keyof ProgressFormValues> = [
  "portfolioValue",
  "investedValue",
  "equityValue",
  "debtValue",
  "cryptoValue",
  "cashValue",
  "monthlyInvestment",
];

function parseNumberField(
  values: ProgressFormValues,
  field: keyof ProgressFormValues,
  errors: ProgressFormErrors,
) {
  const value = values[field].trim();
  const parsedValue = value.length > 0 ? Number(value) : Number.NaN;

  if (!Number.isFinite(parsedValue) || parsedValue < 0) {
    errors[field] = "Enter a valid amount.";
  }

  return parsedValue;
}

export function validateProgressSnapshotForm(values: ProgressFormValues) {
  const errors: ProgressFormErrors = {};

  if (!/^\d{4}-\d{2}$/.test(values.month.trim())) {
    errors.month = "Use YYYY-MM.";
  }

  const parsedValues = Object.fromEntries(
    requiredNumberFields.map((field) => [
      field,
      parseNumberField(values, field, errors),
    ]),
  ) as Record<(typeof requiredNumberFields)[number], number>;
  const trimmedExpense = values.monthlyExpense.trim();
  const trimmedSalary = values.salary.trim();
  const salary = trimmedSalary.length === 0 ? undefined : Number(trimmedSalary);
  const monthlyExpense =
    trimmedExpense.length === 0 ? undefined : Number(trimmedExpense);

  if (salary !== undefined && (!Number.isFinite(salary) || salary < 0)) {
    errors.salary = "Enter a valid amount.";
  }

  if (
    monthlyExpense !== undefined &&
    (!Number.isFinite(monthlyExpense) || monthlyExpense < 0)
  ) {
    errors.monthlyExpense = "Enter a valid amount.";
  }

  if (Object.keys(errors).length > 0) {
    return { errors, snapshot: null };
  }

  return {
    errors,
    snapshot: {
      cashValue: parsedValues.cashValue,
      cryptoValue: parsedValues.cryptoValue,
      debtValue: parsedValues.debtValue,
      equityValue: parsedValues.equityValue,
      id: createId("snapshot"),
      investedValue: parsedValues.investedValue,
      month: values.month.trim(),
      monthlyExpense,
      monthlyInvestment: parsedValues.monthlyInvestment,
      notes: values.notes.trim() || undefined,
      performanceBasis: {
        reason: "manual-snapshot",
        status: "unavailable",
        warnings: [
          "Monthly performance is unavailable because this snapshot has no classified external-flow basis.",
        ],
      },
      portfolioValue: parsedValues.portfolioValue,
      ...(salary === undefined ? {} : { salary }),
    } satisfies MonthlySnapshot,
  };
}

function automationMessage({
  createdCount,
  incomeRefreshedCount,
  provisionalCount,
  refreshedCount,
  status,
  warnings = [],
}: {
  createdCount: number;
  incomeRefreshedCount: number;
  provisionalCount: number;
  refreshedCount: number;
  status: GeneratedSnapshotStatus;
  warnings?: string[];
}) {
  if (warnings.some((warning) => warning.startsWith("Earlier PPF balances"))) {
    return "Full portfolio history needs earlier PPF balances. PPF is excluded from available market and cash trends.";
  }
  if (refreshedCount > 0) {
    return refreshedCount === 1
      ? "1 estimated snapshot updated with better month-end values."
      : `${refreshedCount} estimated snapshots updated with better month-end values.`;
  }

  if (incomeRefreshedCount > 0) {
    if (provisionalCount > 0) {
      return "Newly recorded income was added. Some completed months still use estimated values.";
    }

    return incomeRefreshedCount === 1
      ? "1 snapshot updated with newly recorded income."
      : `${incomeRefreshedCount} snapshots updated with newly recorded income.`;
  }

  if (status === "created") {
    return createdCount === 1
      ? "1 missing month snapshot generated automatically."
      : `${createdCount} missing month snapshots generated automatically.`;
  }

  if (provisionalCount > 0) {
    return "Some completed months still use estimated values.";
  }

  if (status === "already-exists") {
    return "All completed month snapshots are already recorded.";
  }

  return "Not enough portfolio data to generate a completed month snapshot yet.";
}

function automationWarningMessage(targetMonth: string, warning: string) {
  if (warning.includes("PPF account") && warning.includes("confirmed balance checkpoint")) {
    return "Earlier PPF balances are missing. Today's PPF balance cannot be used for past months. Add a confirmed earlier balance only if your statement supports it; market and cash charts exclude PPF until its history is available.";
  }
  if (warning.includes("fallback")) {
    return null;
  }

  if (warning.includes("could not be priced")) {
    return `${targetMonth}: ${warning} Refresh prices or enter a manual price to complete this snapshot.`;
  }

  if (warning.includes("could not be valued")) {
    return `${targetMonth}: ${warning}`;
  }

  return `${targetMonth}: Some portfolio records need review before this month can be completed.`;
}

function getSnapshotAutomationTargetMonths({
  now,
  state,
}: {
  now: Date;
  state: PortfolioStoreState;
}) {
  const lastCompletedMonth = getPreviousCompletedMonth(now);
  const missingMonths = getMissingCompletedSnapshotMonths({
    cashEntries: state.cashEntries,
    existingSnapshots: state.monthlySnapshots,
    now,
    openingPositions: state.openingPositions,
    ppfAccounts: state.ppfAccounts,
    trades: state.trades,
  });
  const provisionalMonths = state.monthlySnapshots
    .filter(
      (snapshot) =>
        snapshot.month <= lastCompletedMonth &&
        isAutoGeneratedSnapshotProvisional(snapshot) &&
        snapshot.generated?.priceEvidence !== undefined,
    )
    .map((snapshot) => snapshot.month);
  const incomeRefreshMonths = state.monthlySnapshots
    .filter(
      (snapshot) =>
        snapshot.month <= lastCompletedMonth &&
        snapshot.generated?.source === "auto" &&
        snapshot.generated.priceEvidence !== undefined &&
        snapshot.salary !==
          deriveMonthlySnapshotSalary(state.cashEntries, snapshot.month),
    )
    .map((snapshot) => snapshot.month);

  return [
    ...new Set([...missingMonths, ...provisionalMonths, ...incomeRefreshMonths]),
  ].sort();
}

function getProvisionalSnapshotMonths({
  lastCompletedMonth,
  snapshots,
}: {
  lastCompletedMonth: string;
  snapshots: MonthlySnapshot[];
}) {
  return snapshots
    .filter(
      (snapshot) =>
        snapshot.month <= lastCompletedMonth &&
        getMonthlySnapshotPriceConfidence(snapshot) === "provisional",
    )
    .map((snapshot) => snapshot.month)
    .sort();
}

function getMonthEndDate(targetMonth: string) {
  const [yearValue, monthValue] = targetMonth.split("-");
  const year = Number(yearValue);
  const monthIndex = Number(monthValue) - 1;

  return new Date(Date.UTC(year, monthIndex + 1, 0, 23, 59, 59, 999));
}

function isOnOrBefore(isoDate: string, maxDate: Date) {
  return new Date(isoDate).getTime() <= maxDate.getTime();
}

function needsHistoricalPrice({
  assetId,
  state,
  targetMonth,
}: {
  assetId: string;
  state: PortfolioStoreState;
  targetMonth: string;
}) {
  const cacheKey = historicalQuoteCacheKey(assetId, targetMonth);
  const cachedQuote = state.historicalQuoteCache[cacheKey];

  if (
    cachedQuote?.currency === "INR" &&
    (cachedQuote.basis === "historical-close" ||
      cachedQuote.basis === "cached-historical-close")
  ) {
    return false;
  }

  const monthEnd = getMonthEndDate(targetMonth);
  const effectiveOpenings = state.openingPositions.filter(
    (position) =>
      position.assetId === assetId &&
      isOnOrBefore(getOpeningPositionHistoryDate(position) ?? "", monthEnd),
  );
  const openingQuantity = state.openingPositions.reduce(
    (quantity, position) =>
      position.assetId === assetId &&
      isOnOrBefore(getOpeningPositionHistoryDate(position) ?? "", monthEnd)
        ? quantity.plus(position.quantity)
        : quantity,
    decimal(0),
  );
  const tradedQuantity = state.trades.reduce((quantity, trade) => {
    if (
      trade.assetId !== assetId ||
      !isOnOrBefore(trade.date, monthEnd) ||
      !isTransactionAfterOpeningCutover(trade.date, effectiveOpenings)
    ) {
      return quantity;
    }

    return quantity.plus(getTradeQuantityDelta(trade));
  }, decimal(0));

  return openingQuantity
    .plus(tradedQuantity)
    .greaterThanOrEqualTo(quantityQuantum);
}

export function useProgress({
  historicalPriceFetcher = resolveHistoricalPrice,
  now = new Date(),
  store = getPortfolioStore(),
}: UseProgressInput = {}) {
  const snapshot = usePortfolioSnapshot(store);
  const currentCalendarMonth = formatLocalCalendarDate(now).slice(0, 7);
  // Keep chart-only partial history out of persisted full-portfolio snapshots.
  // Memoize the multi-month reconstruction, not cheap presentation calculations.
  const ppfExcludedHistory = useMemo(() => buildPpfExcludedChartHistory({
    assets: snapshot.assets,
    cashEntries: snapshot.cashEntries,
    existingSnapshots: snapshot.monthlySnapshots,
    historicalQuotes: snapshot.historicalQuoteCache,
    now: new Date(`${currentCalendarMonth}-15T12:00:00Z`),
    openingPositions: snapshot.openingPositions,
    ppfAccounts: snapshot.ppfAccounts,
    ppfLedgerEntries: snapshot.ppfLedgerEntries,
    quoteCache: snapshot.quoteCache,
    trades: snapshot.trades,
  }), [snapshot.assets, snapshot.cashEntries, snapshot.monthlySnapshots,
    snapshot.historicalQuoteCache, snapshot.openingPositions, snapshot.ppfAccounts,
    snapshot.ppfLedgerEntries, snapshot.quoteCache, snapshot.trades, currentCalendarMonth]);
  const chartSnapshots = ppfExcludedHistory?.snapshots ?? snapshot.monthlySnapshots;
  const [formValues, setFormValues] = useState(emptyProgressFormValues);
  const [errors, setErrors] = useState<ProgressFormErrors>({});
  const [snapshotAutomationStatus, setSnapshotAutomationStatus] =
    useState<ProgressSnapshotAutomationStatus>(() => ({
      message: "Month-end snapshot automation has not run yet.",
      provisionalMonths: [],
      snapshot: null,
      status: "idle",
      targetMonth: getPreviousCompletedMonth(now),
      warnings: [],
    }));
  const [portfolioChartRange, setPortfolioChartRange] =
    useState<MonthlyChartRange>(() =>
      getDefaultMonthlyChartRange(chartSnapshots.length),
    );
  const [assetChartRange, setAssetChartRange] = useState<MonthlyChartRange>(() =>
    getDefaultMonthlyChartRange(chartSnapshots.length),
  );
  const [portfolioChartCustomRange, setPortfolioChartCustomRange] =
    useState<MonthlyChartCustomRange>(() =>
      getDefaultCustomChartRange(chartSnapshots),
    );
  const [assetChartCustomRange, setAssetChartCustomRange] =
    useState<MonthlyChartCustomRange>(() =>
      getDefaultCustomChartRange(chartSnapshots),
    );

  useEffect(() => {
    setPortfolioChartCustomRange((current) =>
      normalizeCustomChartRange(current, chartSnapshots),
    );
    setAssetChartCustomRange((current) =>
      normalizeCustomChartRange(current, chartSnapshots),
    );
  }, [chartSnapshots]);
  const asOf = formatLocalCalendarDate(now);
  const ppfSummary = calculatePpfPortfolioSummary({
    accounts: snapshot.ppfAccounts,
    asOf,
    entries: snapshot.ppfLedgerEntries,
  });
  const linkedLegacyAssetIds = getLinkedLegacyPpfAssetIds(snapshot.ppfAccounts, asOf);
  const holdings = calculateHoldings({
    assets: snapshot.assets,
    openingPositions: snapshot.openingPositions,
    quoteCache: snapshot.quoteCache,
    trades: snapshot.trades,
    now,
  }).filter((holding) => !linkedLegacyAssetIds.has(holding.asset.id));
  const cashBalance = calculateCashBalance(snapshot.cashEntries, now);
  const portfolioValue = calculatePortfolioTotal(
    holdings,
    snapshot.cashEntries,
    now,
    ppfSummary.confirmedBalance,
  );
  const totalInvested = normalizeMoney(
    sumFinancialValues(
      holdings.map(
        (holding) =>
          holding.calculationBasis?.totalInvested ?? holding.totalInvested,
      ),
    ).plus(ppfSummary.investedBasis),
  );
  const baseMonthlyMetrics = calculateCashMonthlyMetrics({
    cashEntries: snapshot.cashEntries,
    now,
    openingPositions: snapshot.openingPositions.filter(
      (position) => !linkedLegacyAssetIds.has(position.assetId),
    ),
    trades: snapshot.trades.filter(
      (trade) => !linkedLegacyAssetIds.has(trade.assetId),
    ),
  });
  const currentMonth = formatLocalCalendarDate(now).slice(0, 7);
  const ppfMonthlyInvestment = normalizeMoney(
    sumFinancialValues(
      snapshot.ppfLedgerEntries
        .filter(
          (entry) =>
            entry.type === "contribution" &&
            entry.date.slice(0, 7) === currentMonth,
        )
        .map((entry) => (entry.type === "contribution" ? entry.amount : 0)),
    ),
  );
  const monthlyInvested = normalizeMoney(
    decimal(baseMonthlyMetrics.invested).plus(ppfMonthlyInvestment),
  );
  const monthlyMetrics = {
    ...baseMonthlyMetrics,
    invested: monthlyInvested,
    investmentRate:
      baseMonthlyMetrics.incomeStatus === "available" &&
      baseMonthlyMetrics.income > 0
        ? normalizeMoney(
            decimal(monthlyInvested)
              .dividedBy(baseMonthlyMetrics.income)
              .times(100),
          )
        : null,
  };
  const allocation = calculateAllocation({
    cashBalance,
    holdings,
    ppfConfirmedBalance: ppfSummary.confirmedBalance,
  });
  const hasData =
    holdings.length > 0 ||
    snapshot.cashEntries.length > 0 ||
    ppfSummary.accounts.length > 0;
  const monthlySummaries = calculateMonthlyProgressSummaries(
    snapshot.monthlySnapshots,
  );
  const latestSummary = monthlySummaries[0];
  const portfolioChartData = buildMonthlyProgressChartData(
    chartSnapshots,
    portfolioChartRange,
    portfolioChartCustomRange,
  );
  const assetChartData = buildMonthlyProgressChartData(
    chartSnapshots,
    assetChartRange,
    assetChartCustomRange,
  );

  function setField(field: keyof ProgressFormValues, value: string) {
    setFormValues((currentValues) => ({
      ...currentValues,
      [field]: value,
    }));
    setErrors((currentErrors) => ({
      ...currentErrors,
      [field]: undefined,
    }));
  }

  function saveSnapshot() {
    const result = validateProgressSnapshotForm(formValues);

    if (!result.snapshot) {
      setErrors(result.errors);
      return false;
    }

    const existingSnapshot = snapshot.monthlySnapshots.find(
      (monthlySnapshot) => monthlySnapshot.month === result.snapshot.month,
    );

    if (existingSnapshot) {
      store.getState().updateMonthlySnapshot({
        ...result.snapshot,
        generated: existingSnapshot.generated
          ? {
              ...existingSnapshot.generated,
              source: "manual",
            }
          : undefined,
        id: existingSnapshot.id,
        performanceBasis:
          existingSnapshot.performanceBasis ?? {
            reason: "legacy-snapshot",
            status: "unavailable",
            warnings: [
              "Monthly performance is unavailable for snapshots recorded before contribution tracking.",
            ],
          },
      });
    } else {
      store.getState().addMonthlySnapshot(result.snapshot);
    }

    setFormValues(emptyProgressFormValues());
    setErrors({});
    return true;
  }

  async function runMonthEndSnapshotAutomation(
    targetMonths: string[],
  ): Promise<MonthEndSnapshotAutomationRunResult> {
    const lastCompletedMonth = getPreviousCompletedMonth(now);
    const restoreEpoch = store.getState().restoreEpoch;
    const cancelledResult: MonthEndSnapshotAutomationRunResult = {
      createdCount: 0, incomeRefreshedCount: 0, lastCompletedMonth,
      provisionalCount: 0, provisionalMonths: [], refreshedCount: 0,
      snapshot: null, status: "insufficient-data", targetMonths: [], warnings: [],
    };
    const warnings: string[] = [];
    const createdSnapshots: MonthlySnapshot[] = [];
    const incomeRefreshedSnapshots: MonthlySnapshot[] = [];
    const refreshedSnapshots: MonthlySnapshot[] = [];

    for (const targetMonth of targetMonths) {
      const state = store.getState();
      const existingSnapshot = state.monthlySnapshots.find(
        (snapshot) => snapshot.month === targetMonth,
      );
      const shouldRefreshPrices =
        existingSnapshot === undefined ||
        (isAutoGeneratedSnapshotProvisional(existingSnapshot) &&
          existingSnapshot.generated?.priceEvidence !== undefined);
      const quoteableAssets = state.assets.filter(
        (asset) => asset.assetClass !== "cash" && asset.assetClass !== "debt",
      );

      for (const asset of quoteableAssets) {
        if (
          !shouldRefreshPrices ||
          !needsHistoricalPrice({ assetId: asset.id, state, targetMonth })
        ) {
          continue;
        }

        const historicalPriceResult = await historicalPriceFetcher({
          asset,
          targetMonth,
        });

        if (store.getState().restoreEpoch !== restoreEpoch) return cancelledResult;

        if (historicalPriceResult.ok) {
          store.getState().upsertHistoricalQuote(historicalPriceResult.quote);
        }
      }

      const refreshedState = store.getState();
      const result = buildGeneratedMonthEndSnapshot({
        assets: refreshedState.assets,
        cashEntries: refreshedState.cashEntries,
        existingSnapshots: refreshedState.monthlySnapshots,
        historicalQuotes: refreshedState.historicalQuoteCache,
        now,
        openingPositions: refreshedState.openingPositions,
        ppfAccounts: refreshedState.ppfAccounts,
        ppfLedgerEntries: refreshedState.ppfLedgerEntries,
        quoteCache: refreshedState.quoteCache,
        refreshIncome: true,
        refreshProvisional: true,
        targetMonth,
        trades: refreshedState.trades,
      });

      warnings.push(
        ...result.warnings.flatMap((warning) => {
          const message = automationWarningMessage(targetMonth, warning);

          return message ? [message] : [];
        }),
      );

      if (result.status === "created" && result.snapshot) {
        const existingSnapshot = refreshedState.monthlySnapshots.find(
          (snapshot) => snapshot.month === targetMonth,
        );

        if (existingSnapshot) {
          if (
            shouldReplaceProvisionalSnapshot(
              existingSnapshot,
              result.snapshot,
            )
          ) {
            store.getState().updateMonthlySnapshot(result.snapshot);
            refreshedSnapshots.push(result.snapshot);
          } else if (
            existingSnapshot.generated?.source === "auto" &&
            existingSnapshot.salary !== result.snapshot.salary
          ) {
            const { salary: _existingSalary, ...snapshotWithoutSalary } =
              existingSnapshot;
            const updatedSnapshot: MonthlySnapshot =
              result.snapshot.salary === undefined
                ? snapshotWithoutSalary
                : {
                    ...existingSnapshot,
                    salary: result.snapshot.salary,
                  };
            store.getState().updateMonthlySnapshot(updatedSnapshot);
            incomeRefreshedSnapshots.push(updatedSnapshot);
          }
        } else {
          store.getState().addMonthlySnapshot(result.snapshot);
          createdSnapshots.push(result.snapshot);
        }
      }
    }

    const completedState = store.getState();
    const latestCompletedSnapshot = [...completedState.monthlySnapshots]
      .filter((monthlySnapshot) => monthlySnapshot.month <= lastCompletedMonth)
      .sort((left, right) => right.month.localeCompare(left.month))[0] ?? null;
    const hasCompletedPortfolioRecord = [
      ...completedState.cashEntries.map((entry) => entry.date),
      ...completedState.openingPositions.map((position) =>
        getOpeningPositionHistoryDate(position),
      ),
      ...completedState.trades.map((trade) => trade.date),
      ...completedState.ppfAccounts.map((account) => account.balanceAsOf),
    ].some(
      (date) =>
        date !== null &&
        isOnOrBefore(date, getMonthEndDate(lastCompletedMonth)),
    );
    const provisionalMonths = getProvisionalSnapshotMonths({
      lastCompletedMonth,
      snapshots: completedState.monthlySnapshots,
    });
    const unresolvedTargetMonths = targetMonths.filter(
      (targetMonth) =>
        !completedState.monthlySnapshots.some(
          (monthlySnapshot) => monthlySnapshot.month === targetMonth,
        ),
    );
    if (warnings.length === 0 && unresolvedTargetMonths.length > 0) {
      warnings.push(
        ...unresolvedTargetMonths.map(
          (targetMonth) =>
            `${targetMonth}: This snapshot could not be completed. Refresh prices or enter a manual price for holdings with pending valuation.`,
        ),
      );
    }
    const provisionalCount = provisionalMonths.length;
    const status: GeneratedSnapshotStatus =
      createdSnapshots.length > 0 || refreshedSnapshots.length > 0
        ? "created"
        : unresolvedTargetMonths.length > 0
          ? "insufficient-data"
        : hasCompletedPortfolioRecord
          ? "already-exists"
          : "insufficient-data";
    const snapshot = latestCompletedSnapshot;

    return {
      createdCount: createdSnapshots.length,
      incomeRefreshedCount: incomeRefreshedSnapshots.length,
      lastCompletedMonth,
      provisionalCount,
      provisionalMonths,
      refreshedCount: refreshedSnapshots.length,
      snapshot,
      status,
      targetMonths,
      warnings: [...new Set(warnings)],
    };
  }

  async function ensureMonthEndSnapshot() {
    const restoreEpoch = store.getState().restoreEpoch;
    if (snapshotAutomationEpochs.get(store) !== restoreEpoch) {
      inFlightSnapshotAutomationRuns.delete(store);
      snapshotAutomationEpochs.set(store, restoreEpoch);
    }
    const requestedLastCompletedMonth = getPreviousCompletedMonth(now);

    while (true) {
      let run = inFlightSnapshotAutomationRuns.get(store);

      if (!run) {
        const state = store.getState();
        const targetMonths = getSnapshotAutomationTargetMonths({ now, state });

        if (targetMonths.length === 0) {
          const latestCompletedSnapshot = [...state.monthlySnapshots]
            .filter(
              (monthlySnapshot) =>
                monthlySnapshot.month <= requestedLastCompletedMonth,
            )
            .sort((left, right) => right.month.localeCompare(left.month))[0] ?? null;
          const hasCompletedPortfolioRecord = [
            ...state.cashEntries.map((entry) => entry.date),
            ...state.openingPositions.map((position) =>
              getOpeningPositionHistoryDate(position),
            ),
            ...state.trades.map((trade) => trade.date),
            ...state.ppfAccounts.map((account) => account.balanceAsOf),
          ].some(
            (date) =>
              date !== null &&
              isOnOrBefore(
                date,
                getMonthEndDate(requestedLastCompletedMonth),
              ),
          );
          const provisionalMonths = getProvisionalSnapshotMonths({
            lastCompletedMonth: requestedLastCompletedMonth,
            snapshots: state.monthlySnapshots,
          });
          const result: MonthEndSnapshotAutomationRunResult = {
            createdCount: 0,
            incomeRefreshedCount: 0,
            lastCompletedMonth: requestedLastCompletedMonth,
            provisionalCount: provisionalMonths.length,
            provisionalMonths,
            refreshedCount: 0,
            snapshot: latestCompletedSnapshot,
            status: hasCompletedPortfolioRecord
              ? "already-exists"
              : "insufficient-data",
            targetMonths,
            warnings: [],
          };

          setSnapshotAutomationStatus({
            message: automationMessage(result),
            provisionalMonths: result.provisionalMonths,
            snapshot: result.snapshot,
            status: result.status,
            targetMonth: result.lastCompletedMonth,
            warnings: result.warnings,
          });

          return result;
        }

        run = runMonthEndSnapshotAutomation(targetMonths);
        inFlightSnapshotAutomationRuns.set(store, run);
        const startedRun = run;
        void startedRun
          .finally(() => {
            if (inFlightSnapshotAutomationRuns.get(store) === startedRun) {
              inFlightSnapshotAutomationRuns.delete(store);
            }
          })
          .catch(() => undefined);
      }

      const result = await run;
      if (store.getState().restoreEpoch !== restoreEpoch) return result;

      if (result.lastCompletedMonth !== requestedLastCompletedMonth) {
        if (inFlightSnapshotAutomationRuns.get(store) === run) {
          inFlightSnapshotAutomationRuns.delete(store);
        }
        continue;
      }

      setSnapshotAutomationStatus({
        message: automationMessage(result),
        provisionalMonths: result.provisionalMonths,
        snapshot: result.snapshot,
        status: result.status,
        targetMonth: result.lastCompletedMonth,
        warnings: result.warnings,
      });

      return result;
    }
  }

  return {
    allocation,
    cashBalance,
    assetChartData,
    assetChartCustomRange,
    assetChartRange,
    ensureMonthEndSnapshot,
    errors,
    formValues,
    hasData,
    investmentRate: monthlyMetrics.investmentRate,
    latestSummary,
    monthlyIncome:
      monthlyMetrics.incomeStatus === "available"
        ? monthlyMetrics.income
        : null,
    monthlyInvestment: monthlyMetrics.invested,
    monthlySummaries,
    portfolioChartData,
    ppfExcludedHistory,
    portfolioChartCustomRange,
    portfolioChartRange,
    portfolioValue,
    preferences: snapshot.preferences,
    saveSnapshot,
    saveSnapshotEdits: saveSnapshot,
    setAssetChartRange,
    setAssetChartCustomRange,
    setField,
    setPortfolioChartRange,
    setPortfolioChartCustomRange,
    snapshotAutomationStatus,
    totalInvested,
  };
}
