import type {
  Asset,
  CashEntry,
  HistoricalPriceBasis,
  HistoricalQuoteCache,
  MonthlySnapshot,
  MonthlySnapshotPriceConfidence,
  MonthlySnapshotPriceEvidence,
  OpeningPosition,
  QuoteCache,
  Trade,
} from "@/src/types";
import {
  formatLocalCalendarDate,
  getCalendarDatePart,
} from "@/src/domain/dates";
import { historicalQuoteCacheKey } from "@/src/types";
import {
  isV1CompatibleQuote,
  isV1SupportedAsset,
} from "@/src/domain/portfolioCurrency";

import {
  calculateCashBalance,
  calculateHoldings,
  calculatePortfolioTotal,
} from "./holdings";
import { buildMonthlyPerformanceBasis } from "./monthlyPerformance";

export type GeneratedSnapshotStatus =
  | "already-exists"
  | "created"
  | "insufficient-data";

export type GeneratedMonthEndSnapshotResult = {
  snapshot: MonthlySnapshot | null;
  status: GeneratedSnapshotStatus;
  warnings: string[];
};

export type BuildGeneratedMonthEndSnapshotInput = {
  assets: Asset[];
  cashEntries: CashEntry[];
  existingSnapshots: MonthlySnapshot[];
  historicalQuotes: HistoricalQuoteCache;
  now: Date;
  openingPositions: OpeningPosition[];
  quoteCache: QuoteCache;
  refreshIncome?: boolean;
  refreshProvisional?: boolean;
  targetMonth?: string;
  trades: Trade[];
};

export function deriveMonthlySnapshotSalary(
  cashEntries: CashEntry[],
  targetMonth: string,
) {
  const currentMonthAdditions = cashEntries.filter(
    (entry) =>
      entry.type === "addition" && isWithinMonth(entry.date, targetMonth),
  );
  const hasLegacyIncome = currentMonthAdditions.some(
    (entry) => entry.purpose === "legacyUncategorized",
  );
  const typedIncome = currentMonthAdditions
    .filter((entry) => entry.purpose === "income")
    .reduce((total, entry) => total + entry.amount, 0);

  return !hasLegacyIncome && typedIncome > 0 ? typedIncome : undefined;
}

export type MissingCompletedSnapshotMonthsInput = Pick<
  BuildGeneratedMonthEndSnapshotInput,
  "cashEntries" | "existingSnapshots" | "now" | "openingPositions" | "trades"
>;

type PriceSelectionBasis = HistoricalPriceBasis;

type PriceSelection = {
  basis: PriceSelectionBasis;
  price?: number;
};

const confirmedPriceBases = new Set<HistoricalPriceBasis>([
  "historical-close",
  "cached-historical-close",
]);

export function getMonthlySnapshotPriceConfidence(
  snapshot: MonthlySnapshot,
): MonthlySnapshotPriceConfidence | "manual" {
  if (!snapshot.generated || snapshot.generated.source === "manual") {
    return "manual";
  }

  if (snapshot.generated.priceEvidence) {
    return snapshot.generated.priceEvidence.every((item) =>
      confirmedPriceBases.has(item.basis),
    )
      ? "confirmed"
      : "provisional";
  }

  if (snapshot.generated.confidence) {
    return snapshot.generated.confidence;
  }

  return confirmedPriceBases.has(snapshot.generated.priceBasis as HistoricalPriceBasis)
    ? "confirmed"
    : "provisional";
}

export function isAutoGeneratedSnapshotProvisional(
  snapshot: MonthlySnapshot,
) {
  return (
    snapshot.generated?.source === "auto" &&
    getMonthlySnapshotPriceConfidence(snapshot) === "provisional"
  );
}

function provisionalEvidenceCount(snapshot: MonthlySnapshot) {
  const evidence = snapshot.generated?.priceEvidence;

  if (!evidence) {
    return null;
  }

  return evidence.filter((item) => !confirmedPriceBases.has(item.basis)).length;
}

function priceEvidenceRegressed(
  existingEvidence: MonthlySnapshotPriceEvidence[],
  candidateEvidence: MonthlySnapshotPriceEvidence[],
) {
  const candidatesByAssetId = new Map(
    candidateEvidence.map((item) => [item.assetId, item]),
  );

  return existingEvidence.some((existingItem) => {
    const candidateItem = candidatesByAssetId.get(existingItem.assetId);

    if (!candidateItem) {
      return true;
    }

    if (
      confirmedPriceBases.has(existingItem.basis) &&
      !confirmedPriceBases.has(candidateItem.basis)
    ) {
      return true;
    }

    return (
      existingItem.basis !== "unavailable" &&
      candidateItem.basis === "unavailable"
    );
  });
}

export function shouldReplaceProvisionalSnapshot(
  existing: MonthlySnapshot,
  candidate: MonthlySnapshot,
) {
  if (
    existing.month !== candidate.month ||
    !isAutoGeneratedSnapshotProvisional(existing) ||
    candidate.generated?.source !== "auto"
  ) {
    return false;
  }

  const existingEvidence = existing.generated?.priceEvidence;
  const candidateEvidence = candidate.generated.priceEvidence;

  if (!candidateEvidence) {
    return false;
  }

  // Aggregate-only metadata predates review provenance. It may contain user
  // corrections that cannot be distinguished from untouched automation.
  if (!existingEvidence) {
    return false;
  }

  const existingAssetIds = new Set(
    existingEvidence.map((item) => item.assetId),
  );
  const candidateAssetIds = new Set(
    candidateEvidence.map((item) => item.assetId),
  );

  if (
    existingAssetIds.size !== candidateAssetIds.size ||
    [...existingAssetIds].some((assetId) => !candidateAssetIds.has(assetId)) ||
    priceEvidenceRegressed(existingEvidence, candidateEvidence)
  ) {
    return false;
  }

  const candidateConfidence = getMonthlySnapshotPriceConfidence(candidate);

  if (candidateConfidence === "confirmed") {
    return true;
  }

  const existingCount = provisionalEvidenceCount(existing);
  const candidateCount = provisionalEvidenceCount(candidate);

  return (
    existingCount !== null &&
    candidateCount !== null &&
    candidateCount < existingCount
  );
}

function formatMonth(date: Date) {
  const year = date.getUTCFullYear();
  const month = String(date.getUTCMonth() + 1).padStart(2, "0");

  return `${year}-${month}`;
}

function getMonthEndDate(targetMonth: string) {
  const [yearValue, monthValue] = targetMonth.split("-");
  const year = Number(yearValue);
  const monthIndex = Number(monthValue) - 1;

  return new Date(year, monthIndex + 1, 0, 12, 0, 0, 0);
}

function isWithinMonth(isoDate: string, targetMonth: string) {
  return getCalendarDatePart(isoDate)?.slice(0, 7) === targetMonth;
}

function isOnOrBefore(isoDate: string, maxDate: Date) {
  const calendarDate = getCalendarDatePart(isoDate);

  return (
    calendarDate !== null && calendarDate <= formatLocalCalendarDate(maxDate)
  );
}

function toSnapshotPriceBasis(
  bases: PriceSelectionBasis[],
): MonthlySnapshot["generated"] extends infer T
  ? T extends { priceBasis: infer P }
    ? P
    : never
  : never {
  if (bases.length === 0) {
    return "unavailable";
  }

  const normalized = new Set(
    bases.map((basis) =>
      basis === "cached-historical-close" ? "historical-close" : basis,
    ),
  );

  if (normalized.size === 1) {
    return [...normalized][0] as
      | "historical-close"
      | "latest-local-fallback"
      | "manual-fallback"
      | "unavailable";
  }

  if (
    normalized.has("unavailable") &&
    normalized.size === 1
  ) {
    return "unavailable";
  }

  return "mixed";
}

function formatHoldingWarning(count: number, message: string) {
  const label = count === 1 ? "holding" : "holdings";

  return `${count} ${label} ${message}.`;
}

function buildWarnings(bases: PriceSelectionBasis[]) {
  const counts = bases.reduce(
    (summary, basis) => {
      if (basis === "latest-local-fallback") {
        summary.latestLocalFallback += 1;
      } else if (basis === "manual-fallback") {
        summary.manualFallback += 1;
      } else if (basis === "unavailable") {
        summary.unavailable += 1;
      }

      return summary;
    },
    {
      latestLocalFallback: 0,
      manualFallback: 0,
      unavailable: 0,
    },
  );
  const warnings: string[] = [];

  if (counts.latestLocalFallback > 0) {
    warnings.push(
      formatHoldingWarning(
        counts.latestLocalFallback,
        "used latest local fallback",
      ),
    );
  }

  if (counts.manualFallback > 0) {
    warnings.push(
      formatHoldingWarning(counts.manualFallback, "used manual price fallback"),
    );
  }

  if (counts.unavailable > 0) {
    warnings.push(
      formatHoldingWarning(counts.unavailable, "could not be priced"),
    );
  }

  return warnings;
}

function selectAssetPrice({
  asset,
  historicalQuotes,
  openingPositions,
  quoteCache,
  targetMonth,
}: {
  asset: Asset;
  historicalQuotes: HistoricalQuoteCache;
  openingPositions: OpeningPosition[];
  quoteCache: QuoteCache;
  targetMonth: string;
}): PriceSelection {
  const historicalQuote =
    historicalQuotes[historicalQuoteCacheKey(asset.id, targetMonth)];

  if (historicalQuote && isV1CompatibleQuote(asset, historicalQuote)) {
    return {
      basis: historicalQuote.basis,
      price: historicalQuote.price,
    };
  }

  const latestQuote = quoteCache[asset.id];

  if (latestQuote && isV1CompatibleQuote(asset, latestQuote)) {
    return {
      basis: "latest-local-fallback",
      price: latestQuote.price,
    };
  }

  const latestManualPrice = [...openingPositions]
    .filter((position) => position.currentPrice !== undefined)
    .sort(
      (left, right) =>
        new Date(right.date).getTime() - new Date(left.date).getTime(),
    )[0]?.currentPrice;

  if (latestManualPrice !== undefined) {
    return {
      basis: "manual-fallback",
      price: latestManualPrice,
    };
  }

  return { basis: "unavailable" };
}

export function getPreviousCompletedMonth(now: Date) {
  const previousMonth = new Date(now.getFullYear(), now.getMonth(), 0);

  return `${previousMonth.getFullYear()}-${String(previousMonth.getMonth() + 1).padStart(2, "0")}`;
}

function monthIndex(monthKey: string) {
  const [yearValue, monthValue] = monthKey.split("-");
  const year = Number(yearValue);
  const month = Number(monthValue);

  if (
    !/^\d{4}-\d{2}$/.test(monthKey) ||
    !Number.isInteger(year) ||
    !Number.isInteger(month) ||
    month < 1 ||
    month > 12
  ) {
    return null;
  }

  return year * 12 + month - 1;
}

function formatMonthIndex(index: number) {
  const year = Math.floor(index / 12);
  const month = (index % 12) + 1;

  return `${year}-${String(month).padStart(2, "0")}`;
}

export function getMissingCompletedSnapshotMonths({
  cashEntries,
  existingSnapshots,
  now,
  openingPositions,
  trades,
}: MissingCompletedSnapshotMonthsInput) {
  const recordMonthIndexes = [
    ...cashEntries.map((entry) => entry.date),
    ...openingPositions.map((position) => position.date),
    ...trades.map((trade) => trade.date),
  ]
    .map((date) => new Date(date))
    .filter((date) => Number.isFinite(date.getTime()))
    .map((date) => monthIndex(formatMonth(date)))
    .filter((index): index is number => index !== null);

  if (recordMonthIndexes.length === 0) {
    return [];
  }

  const firstRecordMonth = Math.min(...recordMonthIndexes);
  const lastCompletedMonth = monthIndex(getPreviousCompletedMonth(now));

  if (lastCompletedMonth === null || firstRecordMonth > lastCompletedMonth) {
    return [];
  }

  const existingMonths = new Set(
    existingSnapshots.map((snapshot) => snapshot.month),
  );
  const missingMonths: string[] = [];

  for (let index = firstRecordMonth; index <= lastCompletedMonth; index += 1) {
    const month = formatMonthIndex(index);

    if (!existingMonths.has(month)) {
      missingMonths.push(month);
    }
  }

  return missingMonths;
}

export function buildGeneratedMonthEndSnapshot({
  assets,
  cashEntries,
  existingSnapshots,
  historicalQuotes,
  now,
  openingPositions,
  quoteCache,
  refreshIncome = false,
  refreshProvisional = false,
  targetMonth: requestedTargetMonth,
  trades,
}: BuildGeneratedMonthEndSnapshotInput): GeneratedMonthEndSnapshotResult {
  const targetMonth = requestedTargetMonth ?? getPreviousCompletedMonth(now);
  const targetMonthIndex = monthIndex(targetMonth);
  const lastCompletedMonthIndex = monthIndex(getPreviousCompletedMonth(now));

  if (
    targetMonthIndex === null ||
    lastCompletedMonthIndex === null ||
    targetMonthIndex > lastCompletedMonthIndex
  ) {
    return {
      snapshot: null,
      status: "insufficient-data",
      warnings: [
        `Target month ${targetMonth} is invalid or has not completed yet.`,
      ],
    };
  }

  const existingSnapshot = existingSnapshots.find(
    (snapshot) => snapshot.month === targetMonth,
  );

  if (
    existingSnapshot &&
    !(
      refreshProvisional &&
      isAutoGeneratedSnapshotProvisional(existingSnapshot)
    ) &&
    !(
      refreshIncome &&
      existingSnapshot.generated?.source === "auto" &&
      existingSnapshot.generated.priceEvidence !== undefined &&
      existingSnapshot.salary !==
        deriveMonthlySnapshotSalary(cashEntries, targetMonth)
    )
  ) {
    return {
      snapshot: existingSnapshot,
      status: "already-exists",
      warnings: [],
    };
  }

  if (
    openingPositions.length === 0 &&
    trades.length === 0 &&
    cashEntries.length === 0
  ) {
    return {
      snapshot: null,
      status: "insufficient-data",
      warnings: [
        "No holdings, trades, or cash entries were available to generate the previous month-end snapshot.",
      ],
    };
  }

  const monthEnd = getMonthEndDate(targetMonth);
  const supportedAssetIds = new Set(
    assets.filter(isV1SupportedAsset).map((asset) => asset.id),
  );
  const monthOpeningPositions = openingPositions.filter(
    (position) =>
      supportedAssetIds.has(position.assetId) &&
      isOnOrBefore(position.date, monthEnd),
  );
  const monthTrades = trades.filter(
    (trade) =>
      supportedAssetIds.has(trade.assetId) &&
      isOnOrBefore(trade.date, monthEnd),
  );
  const monthCashEntries = cashEntries.filter((entry) =>
    isOnOrBefore(entry.date, monthEnd),
  );
  const openQuantityByAssetId = new Map<string, number>();

  for (const position of openingPositions.filter((item) =>
    isOnOrBefore(item.date, monthEnd),
  )) {
    openQuantityByAssetId.set(
      position.assetId,
      (openQuantityByAssetId.get(position.assetId) ?? 0) + position.quantity,
    );
  }

  for (const trade of trades.filter((item) =>
    isOnOrBefore(item.date, monthEnd),
  )) {
    openQuantityByAssetId.set(
      trade.assetId,
      (openQuantityByAssetId.get(trade.assetId) ?? 0) +
        (trade.type === "buy" ? trade.quantity : -trade.quantity),
    );
  }

  const unresolvedOpenAssetCount = [...openQuantityByAssetId].filter(
    ([assetId, quantity]) => quantity > 0 && !supportedAssetIds.has(assetId),
  ).length;

  if (unresolvedOpenAssetCount > 0) {
    return {
      snapshot: null,
      status: "insufficient-data",
      warnings: [
        formatHoldingWarning(
          unresolvedOpenAssetCount,
          "could not be valued because asset metadata is unavailable or unsupported for INR reporting",
        ),
      ],
    };
  }

  if (
    monthOpeningPositions.length === 0 &&
    monthTrades.length === 0 &&
    monthCashEntries.length === 0
  ) {
    return {
      snapshot: null,
      status: "insufficient-data",
      warnings: [
        `No holdings, trades, or cash entries were available to derive for target month ${targetMonth}.`,
      ],
    };
  }

  const relevantAssets = assets.filter((asset) => {
    if (!supportedAssetIds.has(asset.id)) {
      return false;
    }

    const hasOpeningPosition = monthOpeningPositions.some(
      (position) => position.assetId === asset.id,
    );
    const hasTrade = monthTrades.some((trade) => trade.assetId === asset.id);

    return hasOpeningPosition || hasTrade;
  });
  const priceSelectionsByAssetId = new Map(
    relevantAssets.map((asset) => [
      asset.id,
      selectAssetPrice({
        asset,
        historicalQuotes,
        openingPositions: monthOpeningPositions.filter(
          (position) => position.assetId === asset.id,
        ),
        quoteCache,
        targetMonth,
      }),
    ]),
  );
  const snapshotQuoteCache = relevantAssets.reduce<QuoteCache>((cache, asset) => {
    const selection = priceSelectionsByAssetId.get(asset.id);

    if (!selection || selection.price === undefined) {
      return cache;
    }

    cache[asset.id] = {
      assetId: asset.id,
      asOf: now.toISOString(),
      currency: asset.currency,
      price: selection.price,
      source: "manual",
    };

    return cache;
  }, {});
  const holdings = calculateHoldings({
    assets: relevantAssets,
    now: monthEnd,
    openingPositions: monthOpeningPositions,
    quoteCache: snapshotQuoteCache,
    trades: monthTrades,
  });
  const pricedAssets = holdings.map((holding) => ({
    asset: holding.asset,
    selection:
      priceSelectionsByAssetId.get(holding.asset.id) ?? {
        basis: "unavailable" as const,
      },
  }));
  const cashValue = calculateCashBalance(monthCashEntries, monthEnd);
  const equityValue = holdings.reduce((total, holding) => {
    if (
      holding.asset.assetClass === "stock" ||
      holding.asset.assetClass === "etf"
    ) {
      return total + holding.currentValue;
    }

    return total;
  }, 0);
  const debtValue = holdings.reduce((total, holding) => {
    if (holding.asset.assetClass === "debt") {
      return total + holding.currentValue;
    }

    return total;
  }, 0);
  const cryptoValue = holdings.reduce((total, holding) => {
    if (holding.asset.assetClass === "crypto") {
      return total + holding.currentValue;
    }

    return total;
  }, 0);
  const priceBases = pricedAssets.map((item) => item.selection.basis);
  const priceEvidence: MonthlySnapshotPriceEvidence[] = pricedAssets.map(
    ({ asset, selection }) => ({
      assetId: asset.id,
      basis: selection.basis,
      ...(selection.price === undefined ? {} : { price: selection.price }),
    }),
  );
  const confidence: MonthlySnapshotPriceConfidence = priceEvidence.every(
    (item) => confirmedPriceBases.has(item.basis),
  )
    ? "confirmed"
    : "provisional";
  const warnings = buildWarnings(priceBases);
  const salary = deriveMonthlySnapshotSalary(monthCashEntries, targetMonth);
  const snapshot: MonthlySnapshot = {
    cashValue,
    cryptoValue,
    debtValue,
    equityValue,
    generated: {
      confidence,
      generatedAt: now.toISOString(),
      priceBasis: toSnapshotPriceBasis(priceBases),
      priceEvidence,
      source: "auto",
      warnings,
    },
    id: existingSnapshot?.id ?? `snapshot-${targetMonth}`,
    investedValue: holdings.reduce(
      (total, holding) => total + holding.totalInvested,
      0,
    ),
    month: targetMonth,
    monthlyInvestment:
      monthOpeningPositions
        .filter((position) => isWithinMonth(position.date, targetMonth))
        .reduce(
          (total, position) =>
            total + position.quantity * position.averageCostPrice,
          0,
        ) +
      monthTrades
        .filter(
          (trade) =>
            trade.type === "buy" && isWithinMonth(trade.date, targetMonth),
        )
        .reduce((total, trade) => total + trade.totalValue, 0),
    performanceBasis: buildMonthlyPerformanceBasis({
      cashEntries: monthCashEntries,
      openingPositions: monthOpeningPositions,
      targetMonth,
    }),
    portfolioValue: calculatePortfolioTotal(holdings, monthCashEntries),
    ...(salary === undefined ? {} : { salary }),
  };

  return {
    snapshot,
    status: "created",
    warnings,
  };
}
