import type {
  Asset,
  CashEntry,
  HistoricalPriceBasis,
  HistoricalQuoteCache,
  MonthlySnapshot,
  MonthlySnapshotPriceConfidence,
  MonthlySnapshotPriceEvidence,
  OpeningPosition,
  PpfAccount,
  PpfLedgerEntry,
  QuoteCache,
  Trade,
} from "@/src/types";
import {
  calculatePpfPortfolioSummary,
  getPpfAccountOpeningDate,
  getLinkedLegacyPpfAssetIds,
} from "@/src/domain/ppf";
import {
  getOpeningPositionHistoryDate,
  isTransactionAfterOpeningCutover,
} from "@/src/domain/openingPositions";
import {
  formatLocalCalendarDate,
  getCalendarDatePart,
} from "@/src/domain/dates";
import { historicalQuoteCacheKey } from "@/src/types";
import {
  isV1CompatibleQuote,
  isV1SupportedAsset,
} from "@/src/domain/portfolioCurrency";
import { normalizeMonthlySnapshot } from "@/src/domain/financialRecords";
import {
  getTradeQuantityDelta,
  isTradeCashPurchase,
} from "@/src/domain/transactionSemantics";
import {
  decimal,
  normalizeMoney,
  type FinancialDecimalInstance,
  quantityQuantum,
  sumFinancialValues,
} from "@/src/domain/precision";

import {
  calculateCashBalance,
  calculateHoldings,
  calculatePortfolioTotal,
} from "./holdings";
import { buildMonthlyPerformanceBasis } from "./monthlyPerformance";

export type GeneratedSnapshotStatus =
  | "already-exists"
  | "created"
  | "insufficient-data";

export type GeneratedMonthEndSnapshotResult = {
  snapshot: MonthlySnapshot | null;
  status: GeneratedSnapshotStatus;
  warnings: string[];
};

export type BuildGeneratedMonthEndSnapshotInput = {
  assets: Asset[];
  cashEntries: CashEntry[];
  existingSnapshots: MonthlySnapshot[];
  historicalQuotes: HistoricalQuoteCache;
  now: Date;
  openingPositions: OpeningPosition[];
  ppfAccounts?: PpfAccount[];
  ppfLedgerEntries?: PpfLedgerEntry[];
  quoteCache: QuoteCache;
  refreshIncome?: boolean;
  refreshProvisional?: boolean;
  targetMonth?: string;
  trades: Trade[];
};

export function deriveMonthlySnapshotSalary(
  cashEntries: CashEntry[],
  targetMonth: string,
) {
  const currentMonthAdditions = cashEntries.filter(
    (entry) =>
      entry.type === "addition" && isWithinMonth(entry.date, targetMonth),
  );
  const hasLegacyIncome = currentMonthAdditions.some(
    (entry) => entry.purpose === "legacyUncategorized",
  );
  const typedIncome = sumFinancialValues(
    currentMonthAdditions
      .filter((entry) => entry.purpose === "income")
      .map((entry) => entry.amount),
  );

  return !hasLegacyIncome && typedIncome.greaterThan(0)
    ? normalizeMoney(typedIncome)
    : undefined;
}

export type MissingCompletedSnapshotMonthsInput = Pick<
  BuildGeneratedMonthEndSnapshotInput,
  | "cashEntries"
  | "existingSnapshots"
  | "now"
  | "openingPositions"
  | "ppfAccounts"
  | "trades"
>;

type PriceSelectionBasis = HistoricalPriceBasis;

type PriceSelection = {
  basis: PriceSelectionBasis;
  price?: number;
};

const confirmedPriceBases = new Set<HistoricalPriceBasis>([
  "historical-close",
  "cached-historical-close",
]);

export function getMonthlySnapshotPriceConfidence(
  snapshot: MonthlySnapshot,
): MonthlySnapshotPriceConfidence | "manual" {
  if (!snapshot.generated || snapshot.generated.source === "manual") {
    return "manual";
  }

  if (snapshot.generated.priceEvidence) {
    return snapshot.generated.priceEvidence.every((item) =>
      confirmedPriceBases.has(item.basis),
    )
      ? "confirmed"
      : "provisional";
  }

  if (snapshot.generated.confidence) {
    return snapshot.generated.confidence;
  }

  return confirmedPriceBases.has(snapshot.generated.priceBasis as HistoricalPriceBasis)
    ? "confirmed"
    : "provisional";
}

export function isAutoGeneratedSnapshotProvisional(
  snapshot: MonthlySnapshot,
) {
  return (
    snapshot.generated?.source === "auto" &&
    getMonthlySnapshotPriceConfidence(snapshot) === "provisional"
  );
}

function provisionalEvidenceCount(snapshot: MonthlySnapshot) {
  const evidence = snapshot.generated?.priceEvidence;

  if (!evidence) {
    return null;
  }

  return evidence.filter((item) => !confirmedPriceBases.has(item.basis)).length;
}

function priceEvidenceRegressed(
  existingEvidence: MonthlySnapshotPriceEvidence[],
  candidateEvidence: MonthlySnapshotPriceEvidence[],
) {
  const candidatesByAssetId = new Map(
    candidateEvidence.map((item) => [item.assetId, item]),
  );

  return existingEvidence.some((existingItem) => {
    const candidateItem = candidatesByAssetId.get(existingItem.assetId);

    if (!candidateItem) {
      return true;
    }

    if (
      confirmedPriceBases.has(existingItem.basis) &&
      !confirmedPriceBases.has(candidateItem.basis)
    ) {
      return true;
    }

    return (
      existingItem.basis !== "unavailable" &&
      candidateItem.basis === "unavailable"
    );
  });
}

export function shouldReplaceProvisionalSnapshot(
  existing: MonthlySnapshot,
  candidate: MonthlySnapshot,
) {
  if (
    existing.month !== candidate.month ||
    !isAutoGeneratedSnapshotProvisional(existing) ||
    candidate.generated?.source !== "auto"
  ) {
    return false;
  }

  const existingEvidence = existing.generated?.priceEvidence;
  const candidateEvidence = candidate.generated.priceEvidence;

  if (!candidateEvidence) {
    return false;
  }

  // Aggregate-only metadata predates review provenance. It may contain user
  // corrections that cannot be distinguished from untouched automation.
  if (!existingEvidence) {
    return false;
  }

  const existingAssetIds = new Set(
    existingEvidence.map((item) => item.assetId),
  );
  const candidateAssetIds = new Set(
    candidateEvidence.map((item) => item.assetId),
  );

  if (
    existingAssetIds.size !== candidateAssetIds.size ||
    [...existingAssetIds].some((assetId) => !candidateAssetIds.has(assetId)) ||
    priceEvidenceRegressed(existingEvidence, candidateEvidence)
  ) {
    return false;
  }

  const candidateConfidence = getMonthlySnapshotPriceConfidence(candidate);

  if (candidateConfidence === "confirmed") {
    return true;
  }

  const existingCount = provisionalEvidenceCount(existing);
  const candidateCount = provisionalEvidenceCount(candidate);

  return (
    existingCount !== null &&
    candidateCount !== null &&
    candidateCount < existingCount
  );
}

function formatMonth(date: Date) {
  const year = date.getUTCFullYear();
  const month = String(date.getUTCMonth() + 1).padStart(2, "0");

  return `${year}-${month}`;
}

function getMonthEndDate(targetMonth: string) {
  const [yearValue, monthValue] = targetMonth.split("-");
  const year = Number(yearValue);
  const monthIndex = Number(monthValue) - 1;

  return new Date(year, monthIndex + 1, 0, 12, 0, 0, 0);
}

function isWithinMonth(isoDate: string, targetMonth: string) {
  return getCalendarDatePart(isoDate)?.slice(0, 7) === targetMonth;
}

function isOnOrBefore(isoDate: string, maxDate: Date) {
  const calendarDate = getCalendarDatePart(isoDate);

  return (
    calendarDate !== null && calendarDate <= formatLocalCalendarDate(maxDate)
  );
}

function toSnapshotPriceBasis(
  bases: PriceSelectionBasis[],
): MonthlySnapshot["generated"] extends infer T
  ? T extends { priceBasis: infer P }
    ? P
    : never
  : never {
  if (bases.length === 0) {
    return "unavailable";
  }

  const normalized = new Set(
    bases.map((basis) =>
      basis === "cached-historical-close" ? "historical-close" : basis,
    ),
  );

  if (normalized.size === 1) {
    return [...normalized][0] as
      | "historical-close"
      | "latest-local-fallback"
      | "manual-fallback"
      | "unavailable";
  }

  if (
    normalized.has("unavailable") &&
    normalized.size === 1
  ) {
    return "unavailable";
  }

  return "mixed";
}

function formatHoldingWarning(count: number, message: string) {
  const label = count === 1 ? "holding" : "holdings";

  return `${count} ${label} ${message}.`;
}

function buildWarnings(bases: PriceSelectionBasis[]) {
  const counts = bases.reduce(
    (summary, basis) => {
      if (basis === "latest-local-fallback") {
        summary.latestLocalFallback += 1;
      } else if (basis === "manual-fallback") {
        summary.manualFallback += 1;
      } else if (basis === "unavailable") {
        summary.unavailable += 1;
      }

      return summary;
    },
    {
      latestLocalFallback: 0,
      manualFallback: 0,
      unavailable: 0,
    },
  );
  const warnings: string[] = [];

  if (counts.latestLocalFallback > 0) {
    warnings.push(
      formatHoldingWarning(
        counts.latestLocalFallback,
        "used latest local fallback",
      ),
    );
  }

  if (counts.manualFallback > 0) {
    warnings.push(
      formatHoldingWarning(counts.manualFallback, "used manual price fallback"),
    );
  }

  if (counts.unavailable > 0) {
    warnings.push(
      formatHoldingWarning(counts.unavailable, "could not be priced"),
    );
  }

  return warnings;
}

function selectAssetPrice({
  asset,
  historicalQuotes,
  openingPositions,
  quoteCache,
  targetMonth,
}: {
  asset: Asset;
  historicalQuotes: HistoricalQuoteCache;
  openingPositions: OpeningPosition[];
  quoteCache: QuoteCache;
  targetMonth: string;
}): PriceSelection {
  const historicalQuote =
    historicalQuotes[historicalQuoteCacheKey(asset.id, targetMonth)];

  if (historicalQuote && isV1CompatibleQuote(asset, historicalQuote)) {
    return {
      basis: historicalQuote.basis,
      price: historicalQuote.price,
    };
  }

  const latestQuote = quoteCache[asset.id];

  if (latestQuote && isV1CompatibleQuote(asset, latestQuote)) {
    return {
      basis: "latest-local-fallback",
      price: latestQuote.price,
    };
  }

  const latestManualPrice = [...openingPositions]
    .filter(
      (position) =>
        position.manualValuation !== undefined ||
        position.currentPrice !== undefined,
    )
    .sort(
      (left, right) =>
        (getOpeningPositionHistoryDate(right) ?? "").localeCompare(
          getOpeningPositionHistoryDate(left) ?? "",
        ),
    )[0];
  const manualPrice =
    latestManualPrice?.manualValuation?.price ?? latestManualPrice?.currentPrice;

  if (manualPrice !== undefined) {
    return {
      basis: "manual-fallback",
      price: manualPrice,
    };
  }

  return { basis: "unavailable" };
}

export function getPreviousCompletedMonth(now: Date) {
  const previousMonth = new Date(now.getFullYear(), now.getMonth(), 0);

  return `${previousMonth.getFullYear()}-${String(previousMonth.getMonth() + 1).padStart(2, "0")}`;
}

function monthIndex(monthKey: string) {
  const [yearValue, monthValue] = monthKey.split("-");
  const year = Number(yearValue);
  const month = Number(monthValue);

  if (
    !/^\d{4}-\d{2}$/.test(monthKey) ||
    !Number.isInteger(year) ||
    !Number.isInteger(month) ||
    month < 1 ||
    month > 12
  ) {
    return null;
  }

  return year * 12 + month - 1;
}

function formatMonthIndex(index: number) {
  const year = Math.floor(index / 12);
  const month = (index % 12) + 1;

  return `${year}-${String(month).padStart(2, "0")}`;
}

export function getMissingCompletedSnapshotMonths({
  cashEntries,
  existingSnapshots,
  now,
  openingPositions,
  ppfAccounts = [],
  trades,
}: MissingCompletedSnapshotMonthsInput) {
  const recordMonthIndexes = [
    ...cashEntries.map((entry) => entry.date),
    ...openingPositions.map((position) =>
      getOpeningPositionHistoryDate(position),
    ),
    ...trades.map((trade) => trade.date),
    ...ppfAccounts.map((account) => account.balanceAsOf),
  ].filter((date): date is string => date !== null)
    .map((date) => new Date(date))
    .filter((date) => Number.isFinite(date.getTime()))
    .map((date) => monthIndex(formatMonth(date)))
    .filter((index): index is number => index !== null);

  if (recordMonthIndexes.length === 0) {
    return [];
  }

  const firstRecordMonth = Math.min(...recordMonthIndexes);
  const lastCompletedMonth = monthIndex(getPreviousCompletedMonth(now));

  if (lastCompletedMonth === null || firstRecordMonth > lastCompletedMonth) {
    return [];
  }

  const existingMonths = new Set(
    existingSnapshots.map((snapshot) => snapshot.month),
  );
  const missingMonths: string[] = [];

  for (let index = firstRecordMonth; index <= lastCompletedMonth; index += 1) {
    const month = formatMonthIndex(index);

    if (!existingMonths.has(month)) {
      missingMonths.push(month);
    }
  }

  return missingMonths;
}

export function buildGeneratedMonthEndSnapshot({
  assets,
  cashEntries,
  existingSnapshots,
  historicalQuotes,
  now,
  openingPositions,
  ppfAccounts = [],
  ppfLedgerEntries = [],
  quoteCache,
  refreshIncome = false,
  refreshProvisional = false,
  targetMonth: requestedTargetMonth,
  trades,
}: BuildGeneratedMonthEndSnapshotInput): GeneratedMonthEndSnapshotResult {
  const targetMonth = requestedTargetMonth ?? getPreviousCompletedMonth(now);
  const targetMonthIndex = monthIndex(targetMonth);
  const lastCompletedMonthIndex = monthIndex(getPreviousCompletedMonth(now));

  if (
    targetMonthIndex === null ||
    lastCompletedMonthIndex === null ||
    targetMonthIndex > lastCompletedMonthIndex
  ) {
    return {
      snapshot: null,
      status: "insufficient-data",
      warnings: [
        `Target month ${targetMonth} is invalid or has not completed yet.`,
      ],
    };
  }

  const existingSnapshot = existingSnapshots.find(
    (snapshot) => snapshot.month === targetMonth,
  );

  if (
    existingSnapshot &&
    !(
      refreshProvisional &&
      isAutoGeneratedSnapshotProvisional(existingSnapshot)
    ) &&
    !(
      refreshIncome &&
      existingSnapshot.generated?.source === "auto" &&
      existingSnapshot.generated.priceEvidence !== undefined &&
      existingSnapshot.salary !==
        deriveMonthlySnapshotSalary(cashEntries, targetMonth)
    )
  ) {
    return {
      snapshot: existingSnapshot,
      status: "already-exists",
      warnings: [],
    };
  }

  if (
    openingPositions.length === 0 &&
    trades.length === 0 &&
    cashEntries.length === 0 &&
    ppfAccounts.length === 0
  ) {
    return {
      snapshot: null,
      status: "insufficient-data",
      warnings: [
        "No holdings, PPF accounts, trades, or cash entries were available to generate the previous month-end snapshot.",
      ],
    };
  }

  const monthEnd = getMonthEndDate(targetMonth);
  const monthEndCalendarDate = formatLocalCalendarDate(monthEnd);
  const unavailablePpfAccounts = ppfAccounts.filter(
    (account) =>
      account.legacyAssetId === undefined &&
      getPpfAccountOpeningDate(account) <= monthEndCalendarDate &&
      account.balanceAsOf > monthEndCalendarDate,
  );
  if (unavailablePpfAccounts.length > 0) {
    return {
      snapshot: null,
      status: "insufficient-data",
      warnings: [
        `${unavailablePpfAccounts.length} PPF account${unavailablePpfAccounts.length === 1 ? " lacks" : "s lack"} a confirmed balance checkpoint for ${targetMonth}.`,
      ],
    };
  }
  const ppfSummary = calculatePpfPortfolioSummary({
    accounts: ppfAccounts,
    asOf: monthEndCalendarDate,
    entries: ppfLedgerEntries,
  });
  const linkedLegacyAssetIds = getLinkedLegacyPpfAssetIds(
    ppfAccounts,
    monthEndCalendarDate,
  );
  const supportedAssetIds = new Set(
    assets
      .filter(
        (asset) =>
          isV1SupportedAsset(asset) && !linkedLegacyAssetIds.has(asset.id),
      )
      .map((asset) => asset.id),
  );
  const monthOpeningPositions = openingPositions.filter(
    (position) =>
      supportedAssetIds.has(position.assetId) &&
      isOnOrBefore(getOpeningPositionHistoryDate(position) ?? "", monthEnd),
  );
  const monthTrades = trades.filter(
    (trade) =>
      supportedAssetIds.has(trade.assetId) &&
      isOnOrBefore(trade.date, monthEnd) &&
      isTransactionAfterOpeningCutover(
        trade.date,
        monthOpeningPositions.filter(
          (position) => position.assetId === trade.assetId,
        ),
      ),
  );
  const monthCashEntries = cashEntries.filter((entry) =>
    isOnOrBefore(entry.date, monthEnd),
  );
  const openQuantityByAssetId = new Map<string, FinancialDecimalInstance>();

  for (const position of openingPositions.filter(
    (item) =>
      !linkedLegacyAssetIds.has(item.assetId) &&
      isOnOrBefore(getOpeningPositionHistoryDate(item) ?? "", monthEnd),
  )) {
    openQuantityByAssetId.set(
      position.assetId,
      decimal(openQuantityByAssetId.get(position.assetId) ?? 0).plus(
        position.quantity,
      ),
    );
  }

  for (const trade of trades.filter((item) => {
    const effectiveOpenings = monthOpeningPositions.filter(
      (position) => position.assetId === item.assetId,
    );
    return (
      !linkedLegacyAssetIds.has(item.assetId) &&
      isOnOrBefore(item.date, monthEnd) &&
      isTransactionAfterOpeningCutover(item.date, effectiveOpenings)
    );
  })) {
    openQuantityByAssetId.set(
      trade.assetId,
      decimal(openQuantityByAssetId.get(trade.assetId) ?? 0).plus(
        getTradeQuantityDelta(trade),
      ),
    );
  }

  const unresolvedOpenAssetCount = [...openQuantityByAssetId].filter(
    ([assetId, quantity]) =>
      quantity.greaterThanOrEqualTo(quantityQuantum) &&
      !supportedAssetIds.has(assetId),
  ).length;

  if (unresolvedOpenAssetCount > 0) {
    return {
      snapshot: null,
      status: "insufficient-data",
      warnings: [
        formatHoldingWarning(
          unresolvedOpenAssetCount,
          "could not be valued because asset metadata is unavailable or unsupported for INR reporting",
        ),
      ],
    };
  }

  if (
    monthOpeningPositions.length === 0 &&
    monthTrades.length === 0 &&
    monthCashEntries.length === 0 &&
    ppfSummary.accounts.length === 0
  ) {
    return {
      snapshot: null,
      status: "insufficient-data",
      warnings: [
        `No holdings, PPF accounts, trades, or cash entries were available to derive for target month ${targetMonth}.`,
      ],
    };
  }

  const relevantAssets = assets.filter((asset) => {
    if (!supportedAssetIds.has(asset.id)) {
      return false;
    }

    const hasOpeningPosition = monthOpeningPositions.some(
      (position) => position.assetId === asset.id,
    );
    const hasTrade = monthTrades.some((trade) => trade.assetId === asset.id);

    return hasOpeningPosition || hasTrade;
  });
  const priceSelectionsByAssetId = new Map(
    relevantAssets.map((asset) => [
      asset.id,
      selectAssetPrice({
        asset,
        historicalQuotes,
        openingPositions: monthOpeningPositions.filter(
          (position) => position.assetId === asset.id,
        ),
        quoteCache,
        targetMonth,
      }),
    ]),
  );
  const snapshotQuoteCache = relevantAssets.reduce<QuoteCache>((cache, asset) => {
    const selection = priceSelectionsByAssetId.get(asset.id);

    if (!selection || selection.price === undefined) {
      return cache;
    }

    cache[asset.id] = {
      assetId: asset.id,
      asOf: now.toISOString(),
      currency: asset.currency,
      price: selection.price,
      source: "manual",
    };

    return cache;
  }, {});
  const holdings = calculateHoldings({
    assets: relevantAssets,
    now: monthEnd,
    openingPositions: monthOpeningPositions,
    quoteCache: snapshotQuoteCache,
    trades: monthTrades,
  });
  const pendingHoldings = holdings.filter(
    (holding) => holding.valuation.status === "pending",
  );

  if (pendingHoldings.length > 0) {
    return {
      snapshot: null,
      status: "insufficient-data",
      warnings: [
        `${pendingHoldings.length} holding${pendingHoldings.length === 1 ? "" : "s"} could not be valued for ${targetMonth}. Refresh prices or enter a manual fallback before creating this snapshot.`,
      ],
    };
  }
  const pricedAssets = holdings.map((holding) => ({
    asset: holding.asset,
    selection:
      priceSelectionsByAssetId.get(holding.asset.id) ?? {
        basis: "unavailable" as const,
      },
  }));
  const cashValue = calculateCashBalance(monthCashEntries, monthEnd);
  const equityValue = normalizeMoney(
    sumFinancialValues(
      holdings
        .filter(
          (holding) =>
            holding.asset.assetClass === "stock" ||
            holding.asset.assetClass === "etf",
        )
        .map(
          (holding) =>
            holding.calculationBasis?.currentValue ?? holding.currentValue ?? 0,
        ),
    ),
  );
  const debtValue = normalizeMoney(
    sumFinancialValues(
      [
        ...holdings
          .filter((holding) => holding.asset.assetClass === "debt")
          .map(
            (holding) =>
              holding.calculationBasis?.currentValue ?? holding.currentValue ?? 0,
          ),
        ppfSummary.confirmedBalance,
      ],
    ),
  );
  const cryptoValue = normalizeMoney(
    sumFinancialValues(
      holdings
        .filter((holding) => holding.asset.assetClass === "crypto")
        .map(
          (holding) =>
            holding.calculationBasis?.currentValue ?? holding.currentValue ?? 0,
        ),
    ),
  );
  const priceBases = pricedAssets.map((item) => item.selection.basis);
  const priceEvidence: MonthlySnapshotPriceEvidence[] = pricedAssets.map(
    ({ asset, selection }) => ({
      assetId: asset.id,
      basis: selection.basis,
      ...(selection.price === undefined ? {} : { price: selection.price }),
    }),
  );
  const confidence: MonthlySnapshotPriceConfidence = priceEvidence.every(
    (item) => confirmedPriceBases.has(item.basis),
  )
    ? "confirmed"
    : "provisional";
  const warnings = buildWarnings(priceBases);
  const salary = deriveMonthlySnapshotSalary(monthCashEntries, targetMonth);
  const portfolioValue = calculatePortfolioTotal(
    holdings,
    monthCashEntries,
    monthEnd,
    ppfSummary.confirmedBalance,
  );

  if (portfolioValue === null) {
    return {
      snapshot: null,
      status: "insufficient-data",
      warnings: ["Portfolio valuation is incomplete for this month."],
    };
  }

  const snapshot: MonthlySnapshot = {
    cashValue,
    cryptoValue,
    debtValue,
    equityValue,
    generated: {
      confidence,
      generatedAt: now.toISOString(),
      priceBasis: toSnapshotPriceBasis(priceBases),
      priceEvidence,
      source: "auto",
      warnings,
    },
    id: existingSnapshot?.id ?? `snapshot-${targetMonth}`,
    investedValue: normalizeMoney(
      sumFinancialValues(
        [
          ...holdings.map(
            (holding) =>
              holding.calculationBasis?.totalInvested ?? holding.totalInvested,
          ),
          ppfSummary.investedBasis,
        ],
      ),
    ),
    month: targetMonth,
    monthlyInvestment: normalizeMoney(
      sumFinancialValues([
        ...monthOpeningPositions
          .filter(
            (position) =>
              position.date !== null &&
              isWithinMonth(position.date, targetMonth),
          )
          .map((position) =>
            decimal(position.quantity).times(position.averageCostPrice),
          ),
        ...monthTrades
          .filter(isTradeCashPurchase)
          .filter((trade) => isWithinMonth(trade.date, targetMonth))
          .map((trade) => trade.totalValue),
        ...ppfLedgerEntries
          .filter(
            (entry) =>
              entry.type === "contribution" &&
              isWithinMonth(entry.date, targetMonth),
          )
          .map((entry) => (entry.type === "contribution" ? entry.amount : 0)),
      ]),
    ),
    performanceBasis: buildMonthlyPerformanceBasis({
      cashEntries: monthCashEntries,
      openingPositions: monthOpeningPositions,
      ppfLedgerEntries: ppfLedgerEntries.filter((entry) =>
        isOnOrBefore(entry.date, monthEnd),
      ),
      targetMonth,
    }),
    portfolioValue,
    ...(salary === undefined ? {} : { salary }),
  };

  return {
    snapshot: normalizeMonthlySnapshot(snapshot),
    status: "created",
    warnings,
  };
}
