import { getPpfAccountOpeningDate } from "@/src/domain/ppf";
import type { MonthlySnapshot } from "@/src/types";

import {
  buildGeneratedMonthEndSnapshot,
  getMissingCompletedSnapshotMonths,
  isAutoGeneratedSnapshotProvisional,
  type BuildGeneratedMonthEndSnapshotInput,
} from "./monthEndSnapshots";

export type PpfExcludedChartHistory = {
  estimatedMonths: string[];
  excludedPpfAccountCount: number;
  missingMonths: string[];
  snapshots: MonthlySnapshot[];
};

function getMonthEndCalendarDate(month: string) {
  const [year, monthNumber] = month.split("-").map(Number);
  const lastDay = new Date(Date.UTC(year, monthNumber, 0)).getUTCDate();

  return `${month}-${String(lastDay).padStart(2, "0")}`;
}

/**
 * Builds an isolated market-and-cash chart when uncheckpointed PPF history
 * would otherwise prevent a complete historical portfolio snapshot.
 */
export function buildPpfExcludedChartHistory(
  input: BuildGeneratedMonthEndSnapshotInput,
): PpfExcludedChartHistory | null {
  const missingFullMonths = getMissingCompletedSnapshotMonths(input);
  const blockedAccounts = (input.ppfAccounts ?? []).filter((account) =>
    missingFullMonths.some(
      (month) =>
        account.legacyAssetId === undefined &&
        getPpfAccountOpeningDate(account) <= getMonthEndCalendarDate(month) &&
        account.balanceAsOf > getMonthEndCalendarDate(month),
    ),
  );

  if (blockedAccounts.length === 0) {
    return null;
  }

  const linkedLegacyAssetIds = new Set(
    (input.ppfAccounts ?? [])
      .map((account) => account.legacyAssetId)
      .filter((assetId): assetId is string => assetId !== undefined),
  );
  const marketCashInput: BuildGeneratedMonthEndSnapshotInput = {
    ...input,
    assets: input.assets.filter((asset) => !linkedLegacyAssetIds.has(asset.id)),
    existingSnapshots: [],
    openingPositions: input.openingPositions.filter(
      (position) => !linkedLegacyAssetIds.has(position.assetId),
    ),
    ppfAccounts: [],
    ppfLedgerEntries: [],
    trades: input.trades.filter(
      (trade) => !linkedLegacyAssetIds.has(trade.assetId),
    ),
  };
  const marketCashMonths = getMissingCompletedSnapshotMonths(marketCashInput);

  if (marketCashMonths.length === 0) {
    return null;
  }

  let snapshots: MonthlySnapshot[] = [];
  const missingMonths: string[] = [];

  for (const targetMonth of marketCashMonths) {
    const result = buildGeneratedMonthEndSnapshot({
      ...marketCashInput,
      targetMonth,
    });

    if (result.snapshot === null) {
      missingMonths.push(targetMonth);
      snapshots = [];
    } else {
      snapshots = [...snapshots, result.snapshot];
    }
  }

  return {
    estimatedMonths: snapshots
      .filter(isAutoGeneratedSnapshotProvisional)
      .map((snapshot) => snapshot.month),
    excludedPpfAccountCount: blockedAccounts.length,
    missingMonths,
    snapshots,
  };
}
